"use client";

import React, { useState, useMemo, useEffect, useId } from 'react';
import { LineChart, Line, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { Calendar, Download, FileText, Filter } from 'lucide-react';
import Toast from '@/components/Toast';

const baseUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000';

interface ChartData {
  day: string;
  visitors: number;
  accuracy: number;
  performance: number;
  sales: number;
}

interface ReportsProps {
  initialShowrooms: string[];
  initialSelectedShowroom: string;
  initialStartDate: string;
  initialEndDate: string;
}

export default function OfficeReportsClient({ initialShowrooms, initialSelectedShowroom, initialStartDate, initialEndDate }: ReportsProps) {
  const showroomUid = useId();
  const startUid = useId();
  const endUid = useId();
  const [showrooms, setShowrooms] = useState<string[]>(initialShowrooms || []);
  const [selectedShowroom, setSelectedShowroom] = useState<string>(initialSelectedShowroom || '');
  const [startDate, setStartDate] = useState(initialStartDate || '');
  const [endDate, setEndDate] = useState(initialEndDate || '');
  const [toastMessage, setToastMessage] = useState('');
  const [showToast, setShowToast] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [data, setData] = useState<ChartData[]>([]);
  const [reportRows, setReportRows] = useState<Array<{ showroom: string; category: string; customerCount: number; feedbackCount: number }>>([]);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [backendStats, setBackendStats] = useState<null | { totalVisitors: number; avgAccuracy: number; avgPerformance: number }>(null);
  const [isSaleModalOpen, setIsSaleModalOpen] = useState(false);
  const [saleAmount, setSaleAmount] = useState<string>("");
  const [saleDate, setSaleDate] = useState<string>("");
  const [saleNotes, setSaleNotes] = useState<string>("");
  const [role, setRole] = useState<string>("");

  // Fallback fetch if SSR failed to provide showrooms for any reason
  useEffect(() => {
    if (showrooms.length === 0) {
      const loadShowrooms = async () => {
        try {
          const res = await fetch(`${baseUrl}/api/user/showrooms-public`);
          if (!res.ok) throw new Error('Failed to load showrooms');
          const js = await res.json();
          const names: string[] = Array.isArray(js) ? js.map((s: any) => s.name) : (js.showrooms || []).map((s: any) => s.name);
          setShowrooms(names);
          if (names.length && !selectedShowroom) setSelectedShowroom(names[0]);
          if (!startDate || !endDate) {
            const today = new Date();
            const from = new Date(today);
            from.setDate(today.getDate() - 6);
            const toStr = today.toISOString().split('T')[0];
            const fromStr = from.toISOString().split('T')[0];
            setStartDate((prev) => prev || fromStr);
            setEndDate((prev) => prev || toStr);
          }
        } catch (e: any) {
          setToastMessage(e?.message || 'Failed to load showrooms');
          setShowToast(true);
        }
      };
      loadShowrooms();
    }
    // Load role for role-based UI
    try {
      const raw = typeof window !== 'undefined' ? localStorage.getItem('user') : null;
      if (raw) {
        const u = JSON.parse(raw);
        if (u?.role) setRole(u.role);
      }
    } catch { }
  }, []);

  // Auto-generate once when showroom and dates are ready
  useEffect(() => {
    if (!autoGenerated && selectedShowroom && startDate && endDate) {
      handleGenerateReport();
      setAutoGenerated(true);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedShowroom, startDate, endDate]);

  const currentShowroomData = useMemo(() => {
    return { name: selectedShowroom, data };
  }, [selectedShowroom, data]);

  const reversedChartData = useMemo(() => {
    return (currentShowroomData?.data || []).slice().reverse();
  }, [currentShowroomData]);

  const stats = useMemo(() => {
    if (backendStats) {
      const totalSalesFromDays = (data || []).reduce((sum, d) => sum + (Number((d as any).sales) || 0), 0);
      return {
        totalVisitors: backendStats.totalVisitors || 0,
        avgAccuracy: Number(backendStats.avgAccuracy || 0).toFixed(1),
        avgPerformance: Number(backendStats.avgPerformance || 0).toFixed(1),
        totalSales: totalSalesFromDays,
      };
    }
    if (reportRows && reportRows.length > 0) {
      const totalVisitors = reportRows.reduce((s, r) => s + (Number(r.customerCount) || 0), 0);
      const totalFeedbacks = reportRows.reduce((s, r) => s + (Number(r.feedbackCount) || 0), 0);
      const acc = totalVisitors > 0 ? ((totalFeedbacks / totalVisitors) * 100) : 0;
      const perf = acc;
      return {
        totalVisitors,
        avgAccuracy: acc.toFixed(1),
        avgPerformance: perf.toFixed(1),
        totalSales: 0,
      };
    }
    if (!currentShowroomData || !currentShowroomData.data?.length) return null;
    const dd = currentShowroomData.data;
    return {
      totalVisitors: dd.reduce((sum, d) => sum + d.visitors, 0),
      avgAccuracy: (dd.reduce((sum, d) => sum + d.accuracy, 0) / dd.length).toFixed(1),
      avgPerformance: (dd.reduce((sum, d) => sum + d.performance, 0) / dd.length).toFixed(1),
      totalSales: dd.reduce((sum, d) => sum + (Number((d as any).sales) || 0), 0),
    };
  }, [currentShowroomData, reportRows, backendStats]);

  const handleGenerateReport = async () => {
    if (!selectedShowroom) {
      setToastMessage('Please select a showroom');
      setShowToast(true);
      return;
    }
    if (!startDate || !endDate) {
      setToastMessage('Please select a valid date range');
      setShowToast(true);
      return;
    }

    setIsGenerating(true);
    try {
      const token = typeof window !== 'undefined' ? localStorage.getItem('token') : null;
      if (!token) throw new Error('Not authenticated');

      const start = new Date(startDate);
      const end = new Date(endDate);
      start.setHours(0, 0, 0, 0);
      end.setHours(0, 0, 0, 0);

      if (start > end) {
        throw new Error('Start date must be before end date');
      }

      const p = new URLSearchParams();
      p.set('from', start.toISOString().split('T')[0]);
      const endExclusive = new Date(end);
      endExclusive.setDate(endExclusive.getDate() + 1);
      p.set('to', endExclusive.toISOString().split('T')[0]);
      p.set('showroom', selectedShowroom);
      p.set('ts', String(Date.now()));
      const params = new URLSearchParams();
      params.set('from', start.toISOString().split('T')[0]);
      params.set('to', endExclusive.toISOString().split('T')[0]);
      if (selectedShowroom) params.set('showroom', selectedShowroom);
      params.set('ts', String(Date.now()));

      const [dailyRes, repRes] = await Promise.all([
        fetch(`${baseUrl}/api/user/analytics/showroom-daily?${p.toString()}`, {
          headers: { Authorization: `Bearer ${token}` },
          cache: 'no-store',
        }),
        fetch(`${baseUrl}/api/user/analytics/showroom-report?${params.toString()}`, {
          headers: { Authorization: `Bearer ${token}` },
          cache: 'no-store',
        }),
      ]);

      if (!dailyRes.ok) throw new Error('Failed to fetch daily analytics');
      const dailyJson = await dailyRes.json();
      const daysPayload: ChartData[] = Array.isArray(dailyJson.days) ? dailyJson.days.map((d: any) => ({
        day: String(d.day),
        visitors: Number(d.visitors || 0),
        accuracy: Number(d.accuracy || 0),
        performance: Number(d.performance || 0),
        sales: Number(d.sales || 0),
      })) : [];
      setData(daysPayload);
      setBackendStats({
        totalVisitors: Number(dailyJson.totalVisitors || 0),
        avgAccuracy: Number(dailyJson.avgAccuracy || 0),
        avgPerformance: Number(dailyJson.avgPerformance || 0),
      });

      if (!repRes.ok) {
        setReportRows([]);
      } else {
        const repJson = await repRes.json();
        const rows: Array<{ showroom: string; category: string; customerCount: number; feedbackCount: number }>
          = Array.isArray(repJson.rows) ? repJson.rows : [];
        setReportRows(rows);
      }
      setToastMessage('Report generated successfully!');
      setShowToast(true);
    } catch (error: any) {
      setToastMessage(error?.message || 'Failed to generate report');
      setShowToast(true);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownloadExcel = () => {
    if (!currentShowroomData || !stats) {
      setToastMessage('Please generate a report first');
      setShowToast(true);
      return;
    }

    const worksheetData: any[] = [];
    worksheetData.push(['Showroom Report']);
    worksheetData.push([currentShowroomData.name]);
    worksheetData.push([`Generated on: ${new Date().toLocaleDateString()}`]);
    worksheetData.push([`Date Range: ${startDate} to ${endDate}`]);
    worksheetData.push(['', '', '', '', '']);

    worksheetData.push(['Summary Statistics', '', '', '', '']);
    worksheetData.push(['Total Visitors', stats.totalVisitors]);
    worksheetData.push(['Average Accuracy', `${stats.avgAccuracy}%`]);
    worksheetData.push(['Average Performance', `${stats.avgPerformance}%`]);
    worksheetData.push(['Total Sales', `$${stats.totalSales}`]);
    worksheetData.push(['', '', '', '', '']);

    worksheetData.push(['Day', 'Visitors', 'Accuracy %', 'Performance %', 'Sales']);
    currentShowroomData.data.forEach((day) => {
      worksheetData.push([day.day, day.visitors, day.accuracy, day.performance, `$${day.sales}`]);
    });
    import('xlsx').then((XLSX) => {
      const worksheet = XLSX.utils.aoa_to_sheet(worksheetData);
      const workbook = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(workbook, worksheet, 'Reports');
      (worksheet as any)['!cols'] = [{ wch: 20 }, { wch: 15 }, { wch: 15 }, { wch: 15 }, { wch: 15 }];
      XLSX.writeFile(
        workbook as any,
        `${currentShowroomData.name}-report-${new Date().toISOString().split('T')[0]}.xlsx`
      );
      setToastMessage('Excel file downloaded successfully!');
      setShowToast(true);
    }).catch(() => {
      setToastMessage('Failed to load Excel exporter');
      setShowToast(true);
    });
  };

  const handleDownloadPDF = () => {
    if (!currentShowroomData || !stats) {
      setToastMessage('Please generate a report first');
      setShowToast(true);
      return;
    }

    Promise.all([import('jspdf'), import('jspdf-autotable')])
      .then(([jsPDFmod, autoTableMod]) => {
        const jsPDF = (jsPDFmod as any).default || (jsPDFmod as any).jsPDF || jsPDFmod;
        const autoTable = (autoTableMod as any).default || (autoTableMod as any);

        const pdf = new jsPDF();

        pdf.setFontSize(18);
        pdf.text('Showroom Performance Report', 14, 15);

        pdf.setFontSize(14);
        pdf.text(currentShowroomData.name, 14, 25);

        pdf.setFontSize(10);
        pdf.text(`Generated on: ${new Date().toLocaleDateString()}`, 14, 32);
        pdf.text(`Date Range: ${startDate} to ${endDate}`, 14, 38);

        let yPosition = 48;

        pdf.setFontSize(12);
        pdf.text('Summary Statistics', 14, yPosition);
        yPosition += 8;

        const summaryData = [
          ['Total Visitors', stats.totalVisitors.toString()],
          ['Average Accuracy', `${stats.avgAccuracy}%`],
          ['Average Performance', `${stats.avgPerformance}%`],
          ['Total Sales', `$${stats.totalSales}`],
        ];

        autoTable(pdf, {
          head: [['Metric', 'Value']],
          body: summaryData,
          startY: yPosition,
          headStyles: { fillColor: [59, 130, 246], textColor: 255 },
          bodyStyles: { textColor: 50 },
          margin: { left: 14, right: 14 },
        });

        yPosition = (pdf as any).lastAutoTable.finalY + 15;

        pdf.setFontSize(12);
        pdf.text('Daily Performance', 14, yPosition);
        yPosition += 8;

        const tableData = currentShowroomData.data.map((day) => [
          day.day,
          day.visitors.toString(),
          `${day.accuracy}%`,
          `${day.performance}%`,
          `$${day.sales}`,
        ]);

        autoTable(pdf, {
          head: [['Day', 'Visitors', 'Accuracy', 'Performance', 'Sales']],
          body: tableData,
          startY: yPosition,
          headStyles: { fillColor: [59, 130, 246], textColor: 255 },
          bodyStyles: { textColor: 50 },
          margin: { left: 14, right: 14 },
        });

        pdf.save(
          `${currentShowroomData.name}-report-${new Date().toISOString().split('T')[0]}.pdf`
        );
        setToastMessage('PDF file downloaded successfully!');
        setShowToast(true);
      })
      .catch(() => {
        setToastMessage('Failed to load PDF exporter');
        setShowToast(true);
      });
  };

  return (
    <div className="min-h-screen p-8 bg-white">
      <div className="max-w-7xl mx-auto">
        <div className="mb-10">
          <h1 className="text-4xl font-bold text-slate-900 mb-2">Reports</h1>
          <p className="text-slate-600 text-lg">Generate and analyze showroom performance reports</p>
        </div>

        <div className="bg-white rounded-xl shadow-sm border border-slate-100 p-8 mb-10">
          <h2 className="text-xl font-bold text-slate-900 mb-6 flex items-center gap-2">
            <Filter size={20} />
            Filters
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-5 gap-6 items-end">
            <div>
              <label htmlFor={`${showroomUid}-showroom`} className="block text-sm font-bold text-slate-900 mb-3">Select Showroom</label>
              <select
                id={`${showroomUid}-showroom`}
                name="showroom"
                value={selectedShowroom}
                onChange={(e) => setSelectedShowroom(e.target.value)}
                className="w-full px-4 py-3 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-slate-900 transition bg-white text-slate-900 font-medium"
              >
                <option value="">Select a showroom</option>
                {showrooms.map((name) => (
                  <option key={name} value={name}>
                    {name}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label htmlFor={`${startUid}-start`} className="block text-sm font-bold text-slate-900 mb-3">
                <Calendar size={16} className="inline mr-2" />
                Start Date
              </label>
              <input
                type="date"
                id={`${startUid}-start`}
                name="startDate"
                value={startDate}
                onChange={(e) => setStartDate(e.target.value)}
                className="w-full px-4 py-3 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-slate-900 transition"
              />
            </div>

            <div>
              <label htmlFor={`${endUid}-end`} className="block text-sm font-bold text-slate-900 mb-3">
                <Calendar size={16} className="inline mr-2" />
                End Date
              </label>
              <input
                type="date"
                id={`${endUid}-end`}
                name="endDate"
                value={endDate}
                onChange={(e) => setEndDate(e.target.value)}
                className="w-full px-4 py-3 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-slate-900 transition"
              />
            </div>

            <button
              name="generateReport"
              onClick={handleGenerateReport}
              disabled={isGenerating || !selectedShowroom || !startDate || !endDate}
              className="px-4 py-3 bg-blue-600 hover:bg-blue-700 disabled:bg-blue-400 disabled:cursor-not-allowed text-white rounded-lg font-semibold flex items-center justify-center gap-2 transition text-sm"
            >
              <FileText size={16} />
              {isGenerating ? 'Generating...' : 'Generate'}
            </button>

            <div className="flex gap-2">
              <button
                name="downloadExcel"
                onClick={handleDownloadExcel}
                disabled={!data.length}
                className="flex-1 px-3 py-3 bg-green-600 hover:bg-green-700 disabled:bg-green-400 disabled:cursor-not-allowed text-white rounded-lg font-semibold flex items-center justify-center gap-1 transition text-sm"
                title="Download Excel"
              >
                <Download size={16} />
                Excel
              </button>
              <button
                name="downloadPdf"
                onClick={handleDownloadPDF}
                disabled={!data.length}
                className="flex-1 px-3 py-3 bg-red-600 hover:bg-red-700 disabled:bg-red-400 disabled:cursor-not-allowed text-white rounded-lg font-semibold flex items-center justify-center gap-1 transition text-sm"
                title="Download PDF"
              >
                <Download size={16} />
                PDF
              </button>
              {(['admin', 'officeAdmin', 'showroom'].includes(role)) && (
                <button
                  name="addSale"
                  onClick={() => {
                    const today = new Date();
                    const toStr = today.toISOString().split('T')[0];
                    setSaleDate((prev) => prev || toStr);
                    setSaleAmount("");
                    setSaleNotes("");
                    setIsSaleModalOpen(true);
                  }}
                  disabled={!selectedShowroom}
                  className="flex-1 px-3 py-3 bg-slate-900 hover:bg-slate-800 disabled:bg-slate-400 disabled:cursor-not-allowed text-white rounded-lg font-semibold flex items-center justify-center gap-1 transition text-sm"
                  title="Add Sale"
                >
                  Add Sale
                </button>
              )}
            </div>
          </div>
        </div>

        {stats && (
          <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-10">
            <div className="bg-white rounded-xl shadow-sm border border-slate-100 p-6">
              <p className="text-sm font-semibold text-slate-500 uppercase tracking-wider mb-2">Total Visitors</p>
              <p className="text-3xl font-bold text-slate-900">{stats.totalVisitors}</p>
            </div>
            <div className="bg-white rounded-xl shadow-sm border border-slate-100 p-6">
              <p className="text-sm font-semibold text-slate-500 uppercase tracking-wider mb-2">Avg Accuracy</p>
              <p className="text-3xl font-bold text-emerald-600">{stats.avgAccuracy}%</p>
            </div>
            <div className="bg-white rounded-xl shadow-sm border border-slate-100 p-6">
              <p className="text-sm font-semibold text-slate-500 uppercase tracking-wider mb-2">Avg Performance</p>
              <p className="text-3xl font-bold text-blue-600">{stats.avgPerformance}%</p>
            </div>
            <div className="bg-white rounded-xl shadow-sm border border-slate-100 p-6">
              <p className="text-sm font-semibold text-slate-500 uppercase tracking-wider mb-2">Total Sales</p>
              <p className="text-3xl font-bold text-purple-600">${stats.totalSales}</p>
            </div>
          </div>
        )}

        {currentShowroomData && currentShowroomData.data?.length > 0 && (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 mb-10">
            <div className="bg-white rounded-xl shadow-sm border border-slate-100 p-8">
              <h3 className="text-lg font-bold text-slate-900 mb-6">Visitors Trend</h3>
              <ResponsiveContainer width="100%" height={350}>
                <LineChart data={reversedChartData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" vertical={false} />
                  <XAxis dataKey="day" stroke="#94a3b8" />
                  <YAxis stroke="#94a3b8" domain={[0, (dataMax) => (dataMax > 0 ? dataMax : 1)]} />
                  <Tooltip
                    contentStyle={{
                      backgroundColor: '#f8fafc',
                      border: '1px solid #e2e8f0',
                      borderRadius: '8px',
                    }}
                  />
                  <Line
                    type="monotone"
                    dataKey="visitors"
                    stroke="#3b82f6"
                    strokeWidth={3}
                    dot={{ fill: '#3b82f6', r: 5 }}
                    activeDot={{ r: 7 }}
                  />
                </LineChart>
              </ResponsiveContainer>
            </div>

            <div className="bg-white rounded-xl shadow-sm border border-slate-100 p-8">
              <h3 className="text-lg font-bold text-slate-900 mb-6">Performance %</h3>
              <ResponsiveContainer width="100%" height={350}>
                <BarChart data={reversedChartData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" vertical={false} />
                  <XAxis dataKey="day" stroke="#94a3b8" />
                  <YAxis stroke="#94a3b8" />
                  <Tooltip
                    contentStyle={{
                      backgroundColor: '#f8fafc',
                      border: '1px solid #e2e8f0',
                      borderRadius: '8px',
                    }}
                  />
                  <Bar dataKey="performance" fill="#10b981" radius={[8, 8, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>

            <div className="bg-white rounded-xl shadow-sm border border-slate-100 p-8">
              <h3 className="text-lg font-bold text-slate-900 mb-6">Accuracy %</h3>
              <ResponsiveContainer width="100%" height={350}>
                <LineChart data={reversedChartData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" vertical={false} />
                  <XAxis dataKey="day" stroke="#94a3b8" />
                  <YAxis stroke="#94a3b8" />
                  <Tooltip
                    contentStyle={{
                      backgroundColor: '#f8fafc',
                      border: '1px solid #e2e8f0',
                      borderRadius: '8px',
                    }}
                  />
                  <Line
                    type="monotone"
                    dataKey="accuracy"
                    stroke="#f59e0b"
                    strokeWidth={3}
                    dot={{ fill: '#f59e0b', r: 5 }}
                    activeDot={{ r: 7 }}
                  />
                </LineChart>
              </ResponsiveContainer>
            </div>

            <div className="bg-white rounded-xl shadow-sm border border-slate-100 p-8">
              <h3 className="text-lg font-bold text-slate-900 mb-6">Sales</h3>
              <ResponsiveContainer width="100%" height={350}>
                <BarChart data={reversedChartData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" vertical={false} />
                  <XAxis dataKey="day" stroke="#94a3b8" />
                  <YAxis stroke="#94a3b8" />
                  <Tooltip
                    contentStyle={{
                      backgroundColor: '#f8fafc',
                      border: '1px solid #e2e8f0',
                      borderRadius: '8px',
                    }}
                    formatter={(value: any) => `$${value}`}
                  />
                  <Bar dataKey="sales" fill="#8b5cf6" radius={[8, 8, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>

          </div>
        )}

        {!data.length && !isGenerating && (
          <div className="bg-white rounded-xl shadow-sm border border-slate-100 p-12 text-center">
            <FileText size={48} className="mx-auto text-slate-300 mb-4" />
            <h3 className="text-lg font-semibold text-slate-900 mb-2">No Data Available</h3>
            <p className="text-slate-600">
              Select a showroom and date range, then click Generate to view reports
            </p>
          </div>
        )}
      </div>

      {isSaleModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center" onClick={() => setIsSaleModalOpen(false)}>
          <div className="relative bg-white rounded-lg shadow-xl w-full max-w-md mx-4 p-6" onClick={(e) => e.stopPropagation()}>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">Add Sale</h2>
            <form
              onSubmit={async (e) => {
                e.preventDefault();
                if (!selectedShowroom) { setToastMessage('Please select a showroom'); setShowToast(true); return; }
                const amt = Number(saleAmount);
                if (!saleAmount || isNaN(amt) || amt <= 0) { setToastMessage('Enter a valid amount'); setShowToast(true); return; }
                if (!saleDate) { setToastMessage('Select a date'); setShowToast(true); return; }
                try {
                  const token = typeof window !== 'undefined' ? localStorage.getItem('token') : null;
                  if (!token) throw new Error('Not authenticated');
                  const res = await fetch(`${baseUrl}/api/user/sales`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
                    body: JSON.stringify({ showroomBranch: selectedShowroom, amount: amt, notes: saleNotes, date: saleDate }),
                  });
                  if (!res.ok) {
                    const t = await res.text();
                    throw new Error(t || 'Failed to add sale');
                  }
                  setToastMessage('Sale added');
                  setShowToast(true);
                  setIsSaleModalOpen(false);
                  await handleGenerateReport();
                } catch (err: any) {
                  setToastMessage(err?.message || 'Failed to add sale');
                  setShowToast(true);
                }
              }}
              className="space-y-4"
            >
              <div>
                <label className="block text-sm font-bold text-slate-900 mb-2">Amount</label>
                <input type="number" min="0" step="0.01" value={saleAmount} onChange={(e) => setSaleAmount(e.target.value)} className="w-full px-4 py-3 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-slate-900 transition" />
              </div>
              <div>
                <label className="block text-sm font-bold text-slate-900 mb-2">Date</label>
                <input type="date" value={saleDate} onChange={(e) => setSaleDate(e.target.value)} className="w-full px-4 py-3 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-slate-900 transition" />
              </div>
              <div>
                <label className="block text-sm font-bold text-slate-900 mb-2">Notes</label>
                <input type="text" value={saleNotes} onChange={(e) => setSaleNotes(e.target.value)} placeholder="Optional" className="w-full px-4 py-3 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-slate-900 transition" />
              </div>
              <div className="flex gap-3 pt-2">
                <button type="button" onClick={() => setIsSaleModalOpen(false)} className="flex-1 px-4 py-3 border border-slate-200 text-slate-700 rounded-lg hover:bg-slate-50 transition-colors font-medium">Cancel</button>
                <button type="submit" className="flex-1 px-4 py-3 bg-slate-900 text-white rounded-lg hover:bg-slate-800 transition-colors font-medium">Save</button>
              </div>
            </form>
          </div>
        </div>
      )}

      <Toast
        message={toastMessage}
        show={showToast}
        onClose={() => setShowToast(false)}
        duration={3000}
      />
    </div>
  );
}
